site_name: DATU Documentation
site_description: "Documentation hub for the Decentralized Accountable Trust Union"
site_url: "https://datuph.github.io/datu"
nav:
  - Overview:
      - Home: index.md
      - Government Blockchain Explainer: government-blockchain-explainer.md
  - Architecture & Protocol:
      - Reference Architecture: ARCHITECTURE.md
      - Stellar Consensus Protocol: consensus-scp.md
  - Delivery Roadmap:
      - Implementation Plan: IMPLEMENTATION_PLAN.md
      - Project Mobilization: project-mobilization.md
      - Project Progress: project-progress.md
docs_dir: docs
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - toc:
      permalink: true
plugins:
  - search
